
language: ruby

rvm:
  #- 1.8.7 # no, since it doesn't get fun(a, *b, c) or fun0\n.fun1
  #- 1.9.3 # Travis broken September 2017
  #- 2.1.1
  - 2.2.2
  - 2.3.1
  - 2.4.1
  - 2.5.1
  #- jruby-18mode
  - jruby-19mode
  - jruby-20mode

#matrix:
#  include:
#    - rvm: jruby-9.1.13.0
#    #- env: JRUBY_OPTS="--profile.api"

#before_install: gem install bundler
script: bundle exec rspec
branches:
  only:
    - master
  #except:
  #  - master

cache: bundler

